---
- name: Deploy fail2ban custom filters
  ansible.builtin.template:
    src: filter.local.j2
    dest: "/etc/fail2ban/filter.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ fail2ban_filters }}"
  loop_control:
    label: "{{ item.name }}"
  notify: restart fail2ban
  when: fail2ban_filters | length > 0
