---
- name: Network hardening
  ansible.builtin.import_tasks: nft.yaml
  tags: [nftables, network_hardening]

- name: Sysctl hardening
  ansible.builtin.import_tasks: sysctl.yaml
  tags: [sysctl, network_hardening]
