---
- name: validate fail2ban configuration
  ansible.builtin.command: fail2ban-client -t
  changed_when: false
  listen: restart fail2ban
  notify: restart fail2ban service

- name: restart fail2ban service
  ansible.builtin.service:
    name: fail2ban
    state: restarted
