---
app_rules:
  - rich_rule: 'rule family="ipv4" source ipset="group_monitoring" port port="8111" protocol="tcp" accept'
    state: enabled
  - rich_rule: 'rule family="ipv4" source ipset="group_monitoring" port port="8211" protocol="tcp" accept'
    state: enabled
  - rich_rule: 'rule family="ipv4" source ipset="group_monitoring" port port="8311" protocol="tcp" accept'
    state: enabled
  - rich_rule: 'rule family="ipv4" source ipset="group_monitoring" port port="8411" protocol="tcp" accept'
    state: enabled
  - rich_rule: 'rule family="ipv4" source ipset="group_monitoring" port port="8511" protocol="tcp" accept'
    state: enabled
  - rich_rule: 'rule family="ipv4" source ipset="group_app" port port="6379" protocol="tcp" accept' #click redis 13002
    state: enabled
  - rich_rule: 'rule family="ipv4" source ipset="group_app" port port="13002" protocol="tcp" accept' #click keeper
    state: enabled
  - rich_rule: 'rule family="ipv4" source address="138.201.194.90" port port="22" protocol="tcp" accept' #click-app14 for SSL certs
    state: enabled

  # front-apps
  - rich_rule: 'rule family="ipv4" source address="188.40.128.94" port port="13001" protocol="tcp" accept'  #front-app7
    state: enabled
  - rich_rule: 'rule family="ipv4" source address="5.9.106.26" port port="13001" protocol="tcp" accept'     #front-app8
    state: enabled
  - rich_rule: 'rule family="ipv4" source address="116.202.85.53" port port="13001" protocol="tcp" accept'  #front-app9
    state: enabled

  - service: ssh
    state: disabled
