---
logging_rules:
  - service: ssh
    state: disabled
  - rich_rule: 'rule family="ipv4" source ipset="group_all" port port="9200" protocol="tcp" accept'
    state: enabled
  - rich_rule: 'rule family="ipv4" source ipset="group_all" port port="9202" protocol="tcp" accept'
    state: enabled

  #discman server: autoban service
  - rich_rule: 'rule family="ipv4" source address="62.212.95.198" port port="9200" protocol="tcp" accept'
    state: enabled
