---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Install hardening packages
  ansible.builtin.package:
    name: "{{ hardening_packages }}"
    state: present

